version: '3.8'

services:
  couchdb1:
    image: couchdb:3.2.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data1:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 30s
      timeout: 10s
      retries: 3

  couchdb2:
    image: couchdb:3.2.2
    ports:
      - "5985:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couchdb_data2:/opt/couchdb/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984"]
      interval: 30s
      timeout: 10s
      retries: 3

  blockchain_node_1:
    build: .
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - COUCHDB_URL=http://admin:admin@couchdb1:5984
    depends_on:
      couchdb1:
        condition: service_healthy

  blockchain_node_2:
    build: .
    ports:
      - "5002:5000"
    environment:
      - PORT=5000
      - COUCHDB_URL=http://admin:admin@couchdb2:5985
    depends_on:
      couchdb2:
        condition: service_healthy

volumes:
  couchdb_data1:
  couchdb_data2:
